### ISSUE TITLE
App exit by itself when rotation

### ISSUE THREAD

**Issue by dzami** [cohenadair/anglers-log#300]
*EXPECTED BEHAVIOR*
 The users should be able to manage this app in rotation mode and make more easier.

*ACTUAL BEHAVIOR*
 when the users open the app and rotate their phone in rotation mode,then the app exit by itself.

*HOW TO REPRODUCE*
●Install anglers' log on playstore
●open the app
●just trying to rotate the phone in rotation 
 mode
●then the app exit by itself.
 Browser: anglers log  version:1.2.10
 Device: Samsung j7 prime android 7.0

*RECORDING BUG*
https://youtu.be/-YH1w53dJcI

**Comment by cohenadair** [comment]
Thanks for the report, and detailed reproduction steps! I'll look into this ASAP.

**Comment by cohenadair** [comment]
Closing, as this will be resolved in Anglers' Log 2.0.
