### ISSUE TITLE
The look in the catch feature disappears after I change the screen rotation to landscape.

### ISSUE THREAD

**Issue by Explorer00** [cohenadair/anglers-log#301]
#### expected behavior
(the catch feature) runs fine even though I change the screen rotation to landscape

#### Real behavior
When I change the screen rotation to landscape, the Catch feature disappears and pushes back to the main page of the app.

#### How to reproduce
- Download app in play store.
- Run the app.
- Press (+) in the lower right corner.
- fill in all catches.
- change the rotation to landscape.
- the display in the (new catch) feature is lost and pushed back to the app's main page.
- Browser: Anglers' log v1.2.10
- Operating system: xiomi redmi 4A, Android v6.0.1

#### Recording Of The Bug
https://youtu.be/YZzl1BpC3pU

**Comment by cohenadair** [comment]
Likely related to #300, possibly a duplicate.

**Comment by cohenadair** [comment]
Closing, as this will be resolved in Anglers' Log 2.0.
