### ISSUE TITLE
(UR: 1) Notify user when automatic backup fails

### ISSUE THREAD

**Issue by cohenadair** [cohenadair/anglers-log#769]
If automatic backup fails due to network or some other issue, the user should be notified in some way so they know there's a problem and they may need to do a manual backup.

**Testing Scenarios**
- [x] Notify on:
  - [x] App open if auth fails
  - [x] Auto-backup if not connected
  - [x] Auto-backup if not signed in
  - [x] Auto-backup if error
- [x] Request permission on:
  - [x] Startup if backup is set up (updating users)
  - [x] Auto-backup set up
- [x] Tapping notification opens BackupPage
- [x] Start backup, background app, receive notification

**Comment by dpage** [comment]
Further to this, I just realised that my installation had become de-authorised from Google Drive as some point in the past (I was reviewing my app access in Google Drive itself). My automated backups from Angler's Log were apparently failing, but were doing so silently, so it was only pure chance that I was able to fix it.

**Comment by cohenadair** [comment]
Thanks for that information @dpage. That is quite annoying. I'll add this issue to the 2.7 project so it'll be included in the next version.

**Comment by cohenadair** [comment]
Reopening. The local notification isn't shown on Android when the app is in the foreground (tested release build on a real device).

**Comment by cohenadair** [comment]
Issue was I missed an Android configuration step for the notifications plugin: https://pub.dev/packages/flutter_local_notifications#release-build-configuration
