### ISSUE TITLE
No APKs at the releases

### ISSUE THREAD

**Issue by IzzySoft** [cohenadair/anglers-log#853]
APK files are missing from your releases for quite a while. Could you please start attaching them again? Thanks in advance!

**Comment by cohenadair** [comment]
Hi @IzzySoft, they're not included because I don't build APKs anymore. Only AABs are built and uploaded to Google Play. The app can be downloaded for free on Google Play; why do you want an APK?

**Comment by IzzySoft** [comment]
Because there are people without access to Google Play – either intentionally (as they, like me, cut all ties to that walled garden) – or because they simply cannot (device was shipped without Play stuff, sitting behind some big national firewall, etc). That's what my repo is for, where [your app is still listed](https://apt.izzysoft.de/packages/com.cohenadair.anglerslog/) – albeit with a very outdated version.

My updater as well as the repo software cannot deal woth bundles, only with APKs. So it would be much appreciated could you make them available again! Starting with the latest release fully suffices, no need to have all old versions :wink:

**Comment by cohenadair** [comment]
Okay, that shouldn't be a problem. I've added a line item in my pre and post-release ticket (#731).

**Comment by IzzySoft** [comment]
Thanks a lot! Then let me check the updater config at my end to make sure it's picked up (and I cannot forget to check back in a "couple of weeks" :see_no_evil:)… OK, was still enabled – but bound to tag names starting with `android-v`. Am I assuming correctly all tags are now just `v<versionName>` and I should use that instead? Or simply consider all tags, regardless of their name?

**Comment by cohenadair** [comment]
All tags will be `v<versionName`. Since I'm using Flutter now, there's no separate releases for Android vs. iOS. I'll reopen this ticket and comment when I've released the next version, so you receive a notification.

**Comment by cohenadair** [comment]
https://github.com/cohenadair/anglers-log/releases/tag/v2.5.0

**Comment by IzzySoft** [comment]
Thanks – but a big OUCH:

```
Offending libs:
---------------
* Amazon In-App Purchasing (/com/amazon/device/iap): NonFreeComp,NonFreeNet
* BillingClient (/com/android/billingclient): NonFreeComp,NonFreeNet
* Crashlytics (/com/crashlytics): NonFreeComp,Tracking
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Mobile Services (/com/google/android/gms): NonFreeComp
* Google Play Core (/com/google/android/play/core): NonFreeNet,NonFreeComp
* Firebase (/com/google/firebase): NonFreeNet,NonFreeComp
* Firebase Analytics (/com/google/firebase/analytics): NonFreeComp,Tracking
* Firebase Installations (/com/google/firebase/installations): NonFreeNet
* Mapbox SDK Telemetry component (/com/mapbox/android/telemetry): NonFreeComp,Tracking
* Mapbox Android SDK (/com/mapbox): NonFreeComp

11 offenders.
```

Plus a file size of 40 MB (per-app limit in my repo is 30 MB). Can something be done about that? Maybe a libre flavor without those proprietary libraries (marked with `NonFreeCom` aka non-free component above)? Mapbox without the Telemetry part would be "acceptable" (AFAIK there's even a "Mapbox Libre" drop-in replacement, guess it was [MapLibre](https://maplibre.org/), see [here](https://www.maptiler.com/news/2021/01/mapbox-gl-open-source-fork/) for some background), but the rest is a bit too much to have the app count as "libre", especially the Crashlytics and Firebase Analytics (which most likely drag in most of the rest) :cry:

**Comment by cohenadair** [comment]
I'm sorry, but I'm not going to make a special build. It's just not something I'm interested in doing or have the time for.

The large APK size is due to Flutter. Flutter has been optimized for app bundles. The app bundle for this app is only 15 MB.

It sounds like you'll just have to pull the app from your repo. My apologies for any inconvenience.

**Comment by IzzySoft** [comment]
OK – sad, but that's the way to go then. Thanks for all your efforts, though!
