### ISSUE TITLE
Error (Xcode): No file or variants found for asset: assets/sensitive.properties.

### ISSUE THREAD

**Issue by K1ckMan** [cohenadair/anglers-log#870]
Hi, I trying to run app and get error. 

Folder:

<img width="293" alt="image" src="https://github.com/cohenadair/anglers-log/assets/85588715/c70e52da-f81e-4250-9f1b-b51593f98f67">

```
Xcode build done.                                           50.1s
Failed to build iOS app
Error (Xcode): No file or variants found for asset: assets/sensitive.properties.


Could not build the application for the simulator.
Error launching application on iPhone 15.
```

**Comment by cohenadair** [comment]
Hi @K1ckMan,

Yes, that's expected. As the name suggests, that file includes sensitive information (API keys, etc.) and is not tracked in git. You can add a `sensitive.properties` file with the following keys to get the app to compile.

```
clientSender.email=
support.email=
sendGrid.apikey=
revenueCat.apiKey=
visualCrossing.apiKey=
mapbox.apiKey=
worldTides.apiKey=
firebase.secret=
```

**Comment by K1ckMan** [comment]
Thanks for answer, for test launch It is necessary to fill out all the fields? I filled out only the main ones, but the application froze at startup.

<img width="418" alt="image" src="https://github.com/cohenadair/anglers-log/assets/85588715/9e76aa94-923b-4de8-a9f5-55c38387c510">


<img width="784" alt="image" src="https://github.com/cohenadair/anglers-log/assets/85588715/62721d60-ea66-4684-85c4-7306e33d509d">

**Comment by cohenadair** [comment]
It's possible they are all required. I've never tried. If that still doesn't work, you might have to do some debugging to see why `LandingPage` is never dismissed.
